import { useEffect, useState } from "react";
import axios from 'axios'
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Form } from '../components'

const Home: NextPage = () => {
  const [selectedIntegration, setSelectedIntegration] = useState<string | null>(null)
  const [integrationsData, setIntegrationsData] = useState()

  useEffect(() => {
    (
      async () => {
        const response = await axios({
        method: 'GET',
        url: '/api/integrations'
      })

      setIntegrationsData(response.data)
    }
  )()
  }, [])

  console.log('\n---------- LOGGING integrationsData ----------\n', integrationsData)

  return (
    <div className={styles.container}>
      <Head>
        <title>Blinq • Integrations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Blinq</h1>

        <p className={styles.description}>Manage your integrations here</p>

        <p>Available integrations:</p>

        {
          integrationsData &&
          <div>
            <div className={styles.grid}>
              {
                Object.keys(integrationsData).map((integration) => {
                  return (
                    <div
                      key={integration}
                      className={styles.card}
                      onClick={() => setSelectedIntegration(integration)}
                    >
                      {integration}
                      {integrationsData[integration].connected &&
                        <div>
                          <p>Connected: Yes</p>
                          <p>Disconnect</p>
                        </div>
                      }
 
                      {!integrationsData[integration].connected &&
                        <div>
                          <p>Connected: No</p>
                          <p>Connect</p>
                        </div>
                      }
                    </div>
                  )
                })
              }
            </div>

            <div className={styles.grid}>Build here</div>
            <Form integration={selectedIntegration} />
          </div>
        }


      </main>
    </div>
  );
};

export default Home;
